version: '3'
services:
  api:
    build: ./api
    ports: 
      - "8080:8000"
    volumes:
      - ./api:/go/src/app
    networks:
      - mysql-link

  mysqlsrv:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql-link
      
networks:
  mysql-link:
    driver: bridge